Manzane/gorillatrip

app/views/layouts/application.html.erb
config/puma.rb

On ajoute les balises ensemble ;)

Google Analytics tag manager Added

---

db/migrate/20200318180401_remove_duration_from_countries_vaccines.rb
db/schema.rb

Wrong position - should be in countries_travels join table - >    re-do db:migrate

Remove duration from countries_vaccines join table - wrong position

---

app/models/country.rb
app/models/vaccine.rb

N:N relationship - add the relationships has_and_belongs_to_many

relationship for the Country and Vaccine Models

---

app/models/country.rb
app/models/travel.rb
app/models/travel_country.rb
db/migrate/20200318183559_drop_join_table_countries_travels.rb
db/migrate/20200318184517_create_travel_countries.rb
db/schema.rb
test/models/travel_country_test.rb

remove travels_countries join table and redo it with a model, add the missing duration field and add relationship has_many & through for the models travel and country.

remove and re-do join table for travels and countries

---

app/models/country.rb
app/models/travel.rb
db/schema.rb

add association and validation for country and travel models

Association and data validation - country and travel

---

Gemfile
Gemfile.lock
app/models/country.rb
app/services/countries_service.rb
db/migrate/20200319123615_add_alpha2_code_to_country.rb
db/migrate/20200319123647_add_alpha3_code_to_country.rb
db/migrate/20200319123709_add_region_to_country.rb
db/seeds.rb

In order to import countries, alphacodes and region
db:migrate to do

Add columns to the Countries Table

---

Gemfile
Gemfile.lock
app/models/country.rb
app/services/countries_service.rb
db/schema.rb
db/seeds.rb

db:migrate, db:seed and bundle install needed

250 Countries inside the seed 

---

app/services/countries_service.rb
db/migrate/20200319160805_add_french_name_to_country.rb
db/migrate/20200319160832_add_flag_url_to_country.rb
db/schema.rb

2 new columns into table Country
Need to do db:migrate and db:seed

Add french names anf flag url to countries

---

app/models/travel.rb
config/routes.rb

account or no account to be reviewed - strategy talk

routes created 

---

db/schema.rb
db/seeds.rb

data for all tables
2 users
2 travels
251 countries
2 vaccines and one treatment
6  visas
relationships between created travels and countries (IN, TH, KH and LA)
relationships between created visas and countries (IN, TH, KH and LA)
relationships between created vaccines and countries (IN, TH, KH and LA)
needs db:drop create migrate seed

Seed for the entire db

---

app/controllers/travels_controller.rb
app/services/travel_creator.rb
app/services/travel_updater.rb
app/views/travels/edit.html.erb
app/views/travels/index.html.erb
app/views/travels/new.html.erb
app/views/travels/show.html.erb
package.json
yarn.lock

needs a yarn install
edit function doesn't work yet - still working on it

Travels controller & views

---

app/controllers/travels_controller.rb
app/services/travel_updater.rb
app/views/travels/edit.html.erb

but still... not perfect for several countries.

travels edits  slightly improved 

---

app/controllers/vaccines_controller.rb
app/views/vaccines/index.html.erb
app/views/vaccines/show.html.erb

- Index and Show actions
Simple views (index and show)

Vaccines Controller 

---

app/controllers/visas_controller.rb
app/views/visas/index.html.erb
app/views/visas/show.html.erb

- Index and Show actions
Simple views index and show - dependent on country

Visas Controller

---

app/services/travel_updater.rb

Before: updated all
Now: only the good one !

Travel Updater fixed

---

db/migrate/20200322174620_add_columns_to_visas_table.rb
db/migrate/20200322174914_add_columns_to_vaccine_table.rb

Visas: 
- contact_number 
- application (ex: URL)
Vaccines: 
- description
- mandatory(boolean)

Columns added to Visas and Vaccines Tables

---

app/views/travels/edit.html.erb
app/views/travels/new.html.erb
app/views/travels/show.html.erb
app/views/vaccines/index.html.erb
app/views/vaccines/show.html.erb
app/views/visas/index.html.erb
app/views/visas/show.html.erb

Views and display content more readable

---

config/routes.rb

Logged users escape maintenance page

---

app/controllers/travels_controller.rb
app/models/travel.rb
app/services/travel_creator.rb
app/services/travel_updater.rb
app/views/travels/edit.html.erb
app/views/travels/new.html.erb

Params become strong params in the travels controller
travel_countries nested in travel
light changes in the form in order to work.

Strong params travels controller

---

app/services/find_visa.rb
db/migrate/20200318142254_create_visas.rb
db/migrate/20200326165013_add_age_to_visa.rb
db/schema.rb
db/seeds.rb

j'ai scrappé le site https://www.tourdumondiste.com/visas-tour-du-monde et enrogistrer les donné dans la db, jai aussi modifier les migration pour collé aux données recuperer

scraping visa from every country

---

app/controllers/pages_controller.rb
app/views/pages/confidentiality.html.erb
config/routes.rb

add confidentiality page (route - add action in pages controller + view)

Confidentiality

---

app/views/shared/_navbar.html.erb

edit profile, view documents, view travels and add a new travel + Homepage link

Add links in the navbar - help the browsing for dev

---

app/controllers/travel_countries_controller.rb
app/controllers/travels_controller.rb
app/models/continent.rb
app/models/country.rb
app/services/countries_service.rb
app/views/travel_countries/edit.html.erb
app/views/travel_countries/new.html.erb
app/views/travels/edit.html.erb
app/views/travels/new.html.erb
db/migrate/20200401162034_create_continents.rb
db/migrate/20200401162200_add_continent_to_countries.rb
db/schema.rb
db/seeds.rb
test/models/continent_test.rb

Create continent table, add continent_id into countries, seed update… + add grouped_select option in the new and edit forms for travel and travel_countries views

Travels - Grouped_Select (countries by continent)

---

Gemfile
Gemfile.lock
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/shared/_navbar.html.erb
config/locales/devise.views.fr.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/simple_form.fr.yml

Translations configured for user registration, eg...
Thanks to devise-i18n gem
-> bundle install

fr translation for devise views 

---

app/models/country.rb
app/models/vaccine.rb
app/models/vaccine_country.rb
app/services/vaccines_countries_association.rb
app/views/travels/show.html.erb
config/locales/en.yml
config/locales/fr.yml
db/migrate/20200404120308_drop_join_table_countries_vaccines.rb
db/migrate/20200404120602_create_vaccine_countries.rb
db/schema.rb
db/seeds.rb
test/models/vaccine_country_test.rb

Change of the DB schema, drop the old join table, create a new one with "systematic" boolean (db:migrate), update of the seed and travel views accordingly to the previous changes.

Vaccines - DB & seed + display

---

app/views/travels/show.html.erb
config/locales/en.yml
config/locales/fr.yml

Display more information about visas and links to vaccines for more information in order to match with figma

Travel Show (view) 

---

app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/users/show.html.erb
config/locales/en.yml
config/locales/fr.yml
db/migrate/20200409171114_remove_gender_in_users.rb
db/migrate/20200409171305_add_gender_to_users.rb
db/schema.rb
db/seeds.rb

Remove gender (string) in Users, re add it (integer), enum genders, add the collection in the form, fix bug of age if BoD nil

Profile - Gender 

---

app/controllers/documents_controller.rb
app/models/document.rb
app/views/documents/edit.html.erb
app/views/documents/index.html.erb
app/views/documents/new.html.erb
config/locales/en.yml
config/locales/fr.yml
db/migrate/20200409184927_add_document_type_to_documents.rb
db/schema.rb
db/seeds.rb

Add document_type in Documents (integer for enum), set enums, modification of new, edit and index view according to these changes and translations + validates expiration_date only for passport (document_type)

Documents - enums for document_type 

---

Gemfile
app/controllers/travel_countries_controller.rb
app/controllers/travels_controller.rb
app/services/travel_date_updater.rb
app/views/travels/show.html.erb

Set global travel start & end dates thanks to start & end dates for the different stays in the countries if they are multiple.
Take the start date for the first stay and the end date of the last stay:
first_stay = travel_countries.order('start_date ASC').first
@first_date = first_stay.start_date
last_stay = travel_countries.order('end_date DESC').first
@last_date = last_stay.end_date

Global travel dates

---

app/controllers/visa_progressions_controller.rb
app/models/travel.rb
app/models/travel_country.rb
app/models/visa.rb
app/models/visa_progression.rb
app/views/travels/show.html.erb
config/routes.rb
db/migrate/20200410170017_create_visa_progressions.rb
db/schema.rb
test/controllers/visa_progressions_controller_test.rb
test/models/visa_progression_test.rb

- creation of the Visa Progression table with visa_id and travel_country_id references and the boolean done + creation of new routes for create and update of VisaProgression
- add the functionality to choose visa and mark as done + display in the travel show
- add the undone functionality
- add comments for better readability in HTML - Travel Show View

Progression visas

---

app/models/travel_country.rb
app/views/travel_countries/edit.html.erb
app/views/travels/edit.html.erb
app/views/travels/show.html.erb
config/locales/en.yml
config/locales/fr.yml

Disable change of countries (edition -> only dates), beginning of display of the to-list for vaccines

preparation for progression vaccines

---

app/controllers/travel_countries_controller.rb
app/controllers/travels_controller.rb
app/controllers/vaccine_progressions_controller.rb
app/models/stay_vaccine_progression.rb
app/models/travel.rb
app/models/travel_country.rb
app/models/user.rb
app/models/vaccine.rb
app/models/vaccine_progression.rb
app/services/vaccine_progression_constructor.rb
app/services/vaccine_progression_t_constructor.rb
app/views/travels/show.html.erb
config/routes.rb
db/migrate/20200411121632_create_vaccine_progressions.rb
db/migrate/20200411121803_create_stay_vaccine_progressions.rb
db/migrate/20200411171441_add_user_to_vaccine_progression.rb
db/migrate/20200411195239_remove_user_from_vaccine_progression.rb
db/schema.rb
test/controllers/vaccine_progressions_controller_test.rb
test/models/stay_vaccine_progression_test.rb
test/models/vaccine_progression_test.rb

Added the Vaccine Progression functionality with new constructors, one route, changes in th DB schema.

Vaccine progressions

---

app/views/travels/show.html.erb

Fix bug of multiple displays of the same vaccines

Algo for the to-do vaccine Display

---

app/helpers/application_helper.rb
app/models/concerns/travel_onboarding.rb
app/models/travel.rb
app/views/travels/show.html.erb
db/migrate/20200413173508_add_onboarding_completed_at_to_travels.rb
db/schema.rb

"Vaccine, visa and global onboarding progress added to the show of the travel, bootstrap progress bars"

Global progress

---

app/views/shared/_navbar.html.erb
app/views/travels/index.html.erb

add .svg extension for the image_tag

Fix Missing extension - Images

---

app/controllers/travels_controller.rb
app/services/travel_updater.rb

fix the problem of editing dates in a global travel

Fix dates modification in Travel Updater

---

app/models/concerns/travel_onboarding.rb
app/services/travel_date_updater.rb
app/views/travels/show.html.erb

Global progresses updated depending on visas and vaccines (bug with only vaccine, before: no update of the global progress)

Fix algo progress Bar

---

app/controllers/travels_controller.rb
app/models/travel.rb
app/views/documents/edit.html.erb
app/views/documents/new.html.erb

Travel Show View : 
- travel_country display order : start date 
- -> so for visa progress: order by travel_country as well and 
- for the vaccine to be done the order is by id (so asc alpha thx to data in csv)

Display order in the Travel View

---

spec/models/user_spec.rb

add the calculate age test for user model

Model Test (user)

---

app/models/travel.rb
app/models/travel_country.rb
app/views/travels/show.html.erb
spec/models/travel_country_spec.rb
spec/models/travel_spec.rb
spec/models/user_spec.rb

refacto duration calculation into instance method instead to calculate directly into the views + test for them

Duration method in Models and Test

---

app/controllers/travel_countries_controller.rb
app/models/travel_country.rb

add the overlap check in travel_country Model and the alert when user create travel_country that overlaps with another within the same travel.

Dates Overlap

---

package.json
yarn.lock

fix jquery update issue with bootstrap

 downgrade version of Jquery

---

Gemfile
app/controllers/travel_countries_controller.rb
app/models/travel_country.rb
spec/models/travel_country_spec.rb
spec/models/travel_spec.rb
spec/models/user_spec.rb

reinstore overlap checks for travel_countries and add the test for the method in model

Overlap date checks and test

---

app/controllers/documents_controller.rb
app/controllers/travel_countries_controller.rb
app/controllers/travels_controller.rb
app/controllers/vaccine_progressions_controller.rb
app/controllers/visa_progressions_controller.rb
app/javascript/plugins/flatpickr.js
app/models/travel_country.rb
app/services/travel_updater.rb
app/views/travel_countries/edit.html.erb
app/views/travel_countries/new.html.erb
app/views/travels/new.html.erb
config/locales/en.yml
config/locales/fr.yml

update flactpickr in order to avoid end_date < start_date (js + model validation + in the travel and travel_countries updater)
Add the missing translations (controllers -> flash notice)

Flatpickr - start and end dates validation

---

app/models/concerns/travel_onboarding.rb
spec/factories.rb
spec/models/concerns/travel_onboarding_spec.rb
spec/models/document_spec.rb
spec/models/travel_country_spec.rb
spec/models/travel_spec.rb
spec/models/user_spec.rb
spec/models/vaccine_progression_spec.rb
spec/rails_helper.rb
spec/support/database_cleaner.rb

Clean code for test config + create test for onboarding_travel (concerns) and fix a NaN bug in it.

Rspec tests

---

app/views/travels/index.html.erb

fix image_tag for cloudinary -> add condition
cl_image_tag vs image_tag

Uploaded Avatar not displayed

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_travel_show.scss
app/javascript/packs/application.js
app/javascript/plugins/visa.js
app/views/travels/index.html.erb
app/views/travels/show.html.erb

- Design of travel show
- Change [icons](https://heroicons.dev/) on dashboard `pink-card`
- Clean code a bit
------------
Travel show design is almost done. There are still animations to do and remove link card at the bottom of the page. There is a need to improve some details for a better user experience but overall it's okay. I did not work on the nav bar yet. 
> Rendu actuel sur Iphone X

Travel show design

---

app/assets/stylesheets/pages/_travel_show.scss
app/views/travels/show.html.erb

- Fix tabs issues
- Fix systematic vaccines card issues
- Fix spaces between the elements of to do lists
- Fix display issues of selected visas (Thanks @Manzane )
--------------
All works pretty well now. There is still only the "links card" to integrate with a better design to do.
I will do that later.
Next step => Landing page and forms

Fix css issues on travel_show

---

app/assets/stylesheets/pages/_travel_show.scss
app/views/travels/show.html.erb

- Fix the double title in vaccines details 
- Fix the color of `.vaccins .inner-subtitle`

fix some little details on travel show

---

Procfile

heroku pipeline config
